name: Release

on:
  workflow_dispatch:
    inputs:
      dryRun:
        description: "Do a dry run to preview instead of a real release"
        required: true
        default: "true"
      distTag:
        description: "The dist-tag to publish (e.g. beta)"
        required: false
      exactVersion:
        description: "Force an exact version for the release"
        required: false

jobs:
  authorize:
    name: Authorize
    runs-on: ubuntu-latest
    steps:
      - name: ${{ github.actor }} permission check to do a release
        uses: octokit/request-action@v2.0.0
        id: permission_check
        with:
          route: GET /repos/:repository/collaborators/${{ github.actor }}
          repository: ${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: "${{ github.actor }} is ${{ steps.permission_check.outputs.data }}"
      - name: "Authorized."
        if: ${{ fromJson(steps.permission_check.outputs.data).admin == true }}
      - name: "Authorization failed."
        if: ${{ failure() }}

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [authorize]
    strategy:
      matrix:
        node-version: ["12.x"]
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install
        run: |
          npm i -g lerna
          yarn --frozen-lockfile

      - name: Build
        run: yarn setup # build runs as part of bootstrap

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test
        env:
          CI: true